---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/managed-by: quarkus
  name: otel-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-collector-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: otel-collector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/managed-by: quarkus
  name: otel-collector
spec:
  ports:
    - name: grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: health
      port: 13133
      protocol: TCP
      targetPort: 13133
  selector:
    app.kubernetes.io/name: otel-collector
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/managed-by: quarkus
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/managed-by: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/redhat_naps_da/opentelemetry-collector:0.80.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: otel-collector
          ports:
            - containerPort: 4317
              name: grpc
              protocol: TCP
            - containerPort: 13133
              name: health
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /conf
              name: config
              readOnly: false
      initContainers:
        - args:
            - pod
            - -lapp.kubernetes.io/name=jaeger
          image: quay.io/jbride/k8s-wait-for:no-root-v1.7
          imagePullPolicy: IfNotPresent
          name: check-jaeger
      serviceAccountName: otel-collector
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: otel-collector-config.yml
                path: otel-collector-config.yml
            name: otel-collector
            optional: false
          name: config
