apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
configMapGenerator:
  - name: otel-collector
    files:
      - otel-collector-config.yml
generatorOptions:
  disableNameSuffixHash: true # use a static name
resources:
- kubernetes.yml
