apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../amq-broker-app
- ../app-db
- ../app-ldap
- ../otel-collector
- ../jaeger
- ../camel-splitter
- ../camel-processor
- ../camel-aggregator
