apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../mqseries
- ../../../base/app-db
- ../../../base/app-ldap
- ../../../base/otel-collector
- ../../../base/jaeger
- ../camel-splitter
- ../camel-processor
- ../camel-aggregator
