---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: mqseries
  name: mqseries
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mqseries-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: mqseries
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mqseries
  name: mqseries
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: jms
      port: 1414
      protocol: TCP
      targetPort: 1414
  selector:
    app.kubernetes.io/name: mqseries
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mqseries
    app.kubernetes.io/managed-by: quarkus
  name: mqseries
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqseries
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqseries
    spec:
      containers:
        - env:
            - name: MQ_QMGR_NAME
              value: QM1
            - name: MQ_APP_PASSWORD
              value: passw0rd
            - name: MQ_ADMIN_PASSWORD
              value: passw0rd
            - name: LICENSE
              value: accept

          # https://developer.ibm.com/tutorials/mq-setting-up-amqp-with-mq/
          image: quay.io/redhat_naps_da/ibm-mqadvanced-server-dev:9.2.5.0-amd64

          imagePullPolicy: Always
          name: mqseries
          ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 1414
              name: jms
              protocol: TCP
            - containerPort: 9443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: mqseries
